---
name: 'CI tests'

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  ci-tests-all:
    name: 'run all tests'
    runs-on: ubuntu-20.04
    # environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.13.4

      - name: Install Terraform libvirt provider
        run: |
          echo 'deb http://download.opensuse.org/repositories/systemsmanagement:/terraform/Ubuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/systemsmanagement:terraform.list
          curl -fsSL https://download.opensuse.org/repositories/systemsmanagement:terraform/Ubuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/systemsmanagement_terraform.gpg > /dev/null
          sudo apt-get update
          sudo apt-get -y install terraform-provider-libvirt

      - name: Install linting tools
        run: |
          sudo apt-get install -y git python3 python3-pip shellcheck
          python3 -m pip install codespell yamllint jsonlint salt-lint

      - name: codespell
        run: make test-codespell

      - name: shellcheck
        run: make test-shellcheck

      - name: yamllint
        run: make test-yamllint

      - name: jsonlint
        run: make test-jsonlint

      - name: salt-lint
        run: make test-salt-lint

      - name: terraform-format
        run: make test-terraform-format

      - name: terraform-validation
        run: make test-terraform-validation

        # TODO: evaluate if this can be run without actual credentials
        # - name: terraform-plan
        #   run: make test-terraform-plan
